### ISSUE TITLE
Stopping server started using Systemd results in timeout

### ISSUE THREAD

**Issue by timakro** [Bisa/factorio-init#100]
When starting and stopping the server using the Systemd service the stopping action takes the 20 seconds timeout. I tried starting the server using the Systemd service and stopping it using the script directly, this is what I get:

```
tim@timakro:~/factorio/factorio-init$ ./factorio stop
2017-03-12 23:00:27 [CHAT] <server>: Server is being shut down on request
Stopping Factorio: . . cat: /home/tim/factorio/factorio/bin/x64/../../server.pid: No such file or directory
complete!
```

After this the script doesn't return, I need to terminate it using CTRL+C. I tried using a variable to store the data in the pidfile in `stop_service()` instead of reading the file again everytime. This got me rid of the `cat: /home/tim/factorio/factorio/bin/x64/../../server.pid: No such file or directory` error. The Systemd service seems to delete the pidfile when the script still expects it to exist. Unfortunately thats not enough to fix it, the script still doesn't return which probably causes the 20 seconds timeout to kick in.

**Comment by Xiretza** [comment]
Did you change your PIDFile directive in the systemd unit? The default location is `/opt/factorio/server.pid`, which is not what your WRITE_DIR is (`/home/tim/factorio/factorio`).

**Comment by timakro** [comment]
Yes, I changed it to `/home/tim/factorio/factorio/server.pid`.

**Comment by Xiretza** [comment]
Assuming your systemd service runs as `User=factorio`, does your `factorio` user have permission to write to `/home/tim/factorio/factorio/`? Does the PIDFile get created at all?

**Comment by timakro** [comment]
It runs as the user `tim` and has permissions, `/home/tim/factorio/factorio/server.pid` is created.

My config file:
```
#!/bin/bash

# Enable debugging, useful when you want to figure out why
# this script is not behaving the way you expect it to do
DEBUG=0

# What do you want to call this service?
SERVICE_NAME="Factorio"

# Which user/group is running factorio?
# Running any public service as "root" is generally not recommended
USERNAME=tim
USERGROUP=tim

# The absolute path to the factorio directory
FACTORIO_PATH=/home/tim/factorio/factorio
# Server settings file, see data/server-settings.example.json
SERVER_SETTINGS=${FACTORIO_PATH}/data/server-settings.json

# Port on which you want to run the server
PORT=34197

# Save the command/chat/log on server start? Default location /opt/factorio/server.out·
# Setting this to 0 will cause the script to erase the log file on each start
# If you set this to 1 you might want to apply logrotate on the log or it will eventually fill your disk
SAVELOG=0

# Factorio comes packaged in a tarball containing the directory named "factorio"
# when using this scripts update/install command we expect to see this very
# directory. If you want to supply your own update/install tar other than what you can download
# from factorio.com/download-headless you can use this option to tell the script this is ok.
#
# If you place your factorio install within a directory named "factorio" and you update/install
# with the official tarball you can safely ignore this option.
PACKAGE_DIR_NAME=factorio

#
# narcotiq made a sweet update script for factorio and by cloning into this
# you can simply run "factorio update" provided you configure the below arguments
# To install the updater:
#
# git clone https://github.com/narc0tiq/factorio-updater
#

# absolute path to the factorio-updater script
UPDATE_SCRIPT=/home/tim/factorio/factorio-updater/update_factorio.py
# Note that if you set HEADLESS=1 the username/token will not be used as the headless
# download is provided free of charge
HEADLESS=1
UPDATE_USERNAME=you
UPDATE_TOKEN=yourtoken
UPDATE_EXPERIMENTAL=0
UPDATE_TMPDIR=/tmp

# Extras
# Additional binary arguments, these will be sent to the binary when issuing the "start" command
EXTRA_BINARGS=""
```

My Systemd service file:
```
[Unit]
Description=Factorio Server
After=network.target

[Service]
User=tim
Group=tim

# We will store a pid file in your ${WRITE_DIR}/server.pid
# Adjust if you change the write dir of your server
PIDFile=/home/tim/factorio/factorio/server.pid

Type=forking
TimeoutStartSec=20
ExecStart=/home/tim/factorio/factorio-init/factorio start
TimeoutStopSec=20
ExecStop=/home/tim/factorio/factorio-init/factorio stop
RestartSec=20
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by Bisa** [comment]
Hi @timakro  (and thank you @Xiretza for your help, much appreciated!)

First, did you you modify the script in any way tim and are you running the latest commit from master? Also, please enable DEBUG=1 and see if that gives us any more clues as to what it is trying to do.

**Comment by Bisa** [comment]
I think I've figured out what the problem is - I could simply tell you to stick to either systemd or sysv and not mix the two but then I'd not be able to sleep at night ;)

When you stop the service using the script directly after first telling systemd to keep track of it systemd will actually clean up the pidfile once the process exits cleanly - in the scripts shutdown loop however I'm not sanity checking that the pid file exists before we try to use it hence the "cat not finding the file"-error.

I'll see what I can cook up to fix this, thnx for reporting it =)

**Comment by timakro** [comment]
Thanks a lot for your help! Starting the server using Systemd and stopping it using the script directly (or installing it in SysVinit) works now, the error and the hanging terminal are gone. Although I still get the timeout when starting and stopping the server using Systemd, no idea what might cause this though.

After stopping the server using Systemd and waiting for the 20 second timeout `systemctl status factorio -l` looks like this:

```
● factorio.service - Factorio Server
   Loaded: loaded (/home/tim/factorio/factorio-init/factorio.service)
   Active: failed (Result: timeout) since Tue 2017-03-14 16:24:10 CET; 5s ago
  Process: 12839 ExecStop=/home/tim/factorio/factorio-init/factorio stop (code=killed, signal=TERM)
  Process: 12804 ExecStart=/home/tim/factorio/factorio-init/factorio start (code=exited, status=0/SUCCESS)
 Main PID: 12823 (code=exited, status=0/SUCCESS)

Mar 14 16:21:33 timakro factorio[12804]: Started Factorio, please see log for details
Mar 14 16:21:33 timakro systemd[1]: Started Factorio Server.
Mar 14 16:23:48 timakro systemd[1]: Stopping Factorio Server...
Mar 14 16:24:08 timakro systemd[1]: factorio.service stopping timed out. Terminating.
Mar 14 16:24:10 timakro systemd[1]: Stopped Factorio Server.
Mar 14 16:24:10 timakro systemd[1]: Unit factorio.service entered failed state.
```

**Comment by Bisa** [comment]
give this one a shot will you @timakro - I've tried various setups including stopping and starting alternating between sysv and systemd, #thisshouldsolveeverything ;)

**Comment by timakro** [comment]
Indeed, #thishassolvedeverything! Thanks again!
