### ISSUE TITLE
Change Savegame / new Game

### ISSUE THREAD

**Issue by Nerdodactylus** [Bisa/factorio-init#104]
Maybe a dumb question, but how do I start a new game?

I tried to delete every savegame in the saves folder and put a new one in there, also changed the filname to one of those autosavegame names. 

Everytime it created a new savegame with my old base. 
I also stopped the service first... not sure how to do it.
Can anyone help?

thank you, 
Nerdodactylus

**Comment by Bisa** [comment]
Try this:
`factorio new-game <the name of your new game>`
optionally, you can specify the path to a map-gen-settings.json as well (relative to your write dir)
`factorio new-game <the name of your new game> data/map-gen-settings.example.json`

**Comment by Bisa** [comment]
@Nerdodactylus - feel free to reopen this issue if you still are unable to create new save games
