### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by TheEisbaer** [Bisa/factorio-init#106]
I have CentOS Linux release 7.3.1611
I don't understand the installation instructions.
Can anyone help me?

**Comment by TheEisbaer** [comment]
Hi, 

when I try to install this script at 
`  systemctl status -l factorio`

I get the following output:
```
Unit factorio.service entered failed state.
factorio.service failed.
```

**Comment by Bisa** [comment]
Hi, not sure - did you follow the install instructions outlined [here](https://github.com/Bisa/factorio-init/blob/master/README.md#install)?

(you can also look at the [debugging](https://github.com/Bisa/factorio-init/blob/master/README.md#debugging) section)

**Comment by BioSLuDge** [comment]
I'm having the same issue.  When I run it with invocation I see the error 
"factorio: line 42: LATEST_HEADLESS_URL: unbound variable"

**Comment by Bisa** [comment]
feel free to reopen if you still have any problems, I hope the debugging and install sections helped you resolve this issue
