### ISSUE TITLE
Can't start server without generate config.ini through starting the server manually...

### ISSUE THREAD

**Issue by buson94** [Bisa/factorio-init#109]
I prepared my server as far as i could with your insctructions but when i do "systemctl start factorio" it exits with a failure. After some time looking for the problem i found out that the config.ini is missing. Because i couldn't generate a .ini through starting the server manually (because it needs the ini first??)... i don't know what to do anymore. Can you help me with the ini please? Hopefully this is the only problem. factorio-init with the factorio-updater should be configured right, the factorio version is downloaded and a save also already exists.

**Comment by Bisa** [comment]
Hi, you used to have to "init" the ini-file by starting the server manually, however with the latest addition to the script to install I seem to have omitted that from the readme, sorry =)

Is using `./factorio install` an option for you? Else you can always start the server as the factorio user `sudo -u factorio /path/to/factorio/bin/factorio` and work your way from there.

(let me know if you run into any snags and I'll see if I can help you along)

**Comment by buson94** [comment]
Thanks for your reply :)
I figured it out by myself, that i need to start the factorio file from the factorio/bin/ folder. Everything works now! (That's the first time i set up a game server on my own) Thanks for making this script!
