### ISSUE TITLE
players displays list heading after list

### ISSUE THREAD

**Issue by dgw** [Bisa/factorio-init#116]
The output of the `players` command is inverted:

````
dgw@factorio-server /opt/factorio# service factorio players
  Bunny5390
  Owningmatt93
  dgw
Players (3):
````

**Comment by Bisa** [comment]
I take it you would prefer if it was output like so?

> dgw@factorio-server /opt/factorio# service factorio players
> Players (3):
>   Bunny5390
>   Owningmatt93
>   dgw
>

**Comment by dgw** [comment]
Right, it's weird that the heading is below the list it describes.
