### ISSUE TITLE
Running server with custon arguments (debian 8)

### ISSUE THREAD

**Issue by BladeRavinger** [Bisa/factorio-init#119]
I have spent the day trying to get a factorio server running. this script would not download the game so i did it manually and using the script installed from tar.

before that i had to update the username/usergroup from factorio to a user i had created. then changed the install and run DIR from /opt/ to one of my choosing, within the users /home/ dir

my log file is as follows 

`   0.023 Program arguments: "/true/path/to/factorio/bin/" "--config" "/path/to/config.ini" "--port" "34197" "--start-server-load-latest" "--server-settings" "/path/to/server-settings.json" 
   0.023 Read data path: /path/to/factorio/data
   0.023 Write data path: /path/to/factorio
   0.023 Binaries path: /path/to/factorio/bin
   0.031 System info: [CPU: Intel Core Processor (Haswell, no TSX), 1 core, RAM: 3869MB]
   0.031 Running in headless mode
   0.034 Loading mod core 0.0.0 (data.lua)
   0.039 Loading mod base 0.15.34 (data.lua)
   0.136 Loading mod base 0.15.34 (data-updates.lua)
   0.167 Checksum for core: 1519575497
   0.167 Checksum of base: 1503927233
   0.275 Info PlayerData.cpp:58: Local player-data.json available, timestamp 1505732291
   0.275 Info PlayerData.cpp:65: Cloud player-data.json unavailable
   0.276 Custom inputs active: 0
   0.276 Factorio initialised
   0.277 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
   0.277 Info ServerMultiplayerManager.cpp:671: mapTick(-1) changing state from(Ready) to(Closed)
   0.285 Goodbye`

i have no idea why it just shuts down, with and without the deamon

**Comment by BladeRavinger** [comment]
server is currently running fine using manual start commands, mounted in screen

**Comment by Bisa** [comment]
Not sure if ur still around, if you are and in need of help - feel free to reopen :)
