### ISSUE TITLE
Can't start factorio from systemctl (Ubuntu 16.04)

### ISSUE THREAD

**Issue by HildarTheDorf** [Bisa/factorio-init#122]
Running factorio-init from systemctl gives "Error InterruptibleStdioStream.cpp:54: Reading stdin failed" in the factorio-current.log, killing the server

Running "factorio foreground" manually gives "/opt/factorio-init/factorio: line 238: fg: no job control"

Running "factorio start" manually succeeds

**Comment by HildarTheDorf** [comment]
Reverting to before the foreground feature was added (i.e. commit add86face82edd4570fe4deab4aa36f8b05b1b4f) works fine.

**Comment by Bisa** [comment]
oups, that's embarrassing - I was a bit to quick to merge the open requests last night, I'll see if I can fix it and/or revert the change

**Comment by jajmo** [comment]
This is occurring now on Ubuntu 18.04, running Factorio 0.17.54.

The symptoms are exactly the same as Hildar described.
