### ISSUE TITLE
Automated Tests

### ISSUE THREAD

**Issue by Bisa** [Bisa/factorio-init#123]
Since the script has become such a large set of logic I would prefer if it could be tested to ensure quality.

**Comment by tmzasz** [comment]
I would not be 100% sure on how to use it but my research points to this
https://github.com/sstephenson/bats
as being a posible testing suite for automated tests if it helps :)

**Comment by jhawkwind** [comment]
Also, if there was a defined subset of *nix "flavors" to target these tests, it would help narrow the field of work, both from a testing perspective and a development perspective.

I would suggest targeting:
* Ubuntu
* CentOS

I don't know if there are any other flavors that are more common than those two among the Factorio community? Also, might want to look at https://travis-ci.com/ integration to help with the testing hooks with GitHub.

**Comment by Bisa** [comment]
note to @Bisa - remember to adjust the default tests to run on "latest" factorio, not some hard coded default.

**Comment by Bisa** [comment]
With the release of 3.0.0 I'll retire this ticket, while tests are not automatic they are at least introduced into the repository and can be built upon going forward.
