### ISSUE TITLE
"awk" invocation under "send_cmd)" hangs due to "-F" flag on "tail"

### ISSUE THREAD

**Issue by NopeDK** [Bisa/factorio-init#132]
As per title, https://github.com/Bisa/factorio-init/blob/20e60dd9b2c1bc15987cf067c73ba16b590195a2/factorio#L273

Solution: remove the "-F" flag.

New problem: If the output of the command is not available at "tail" time, mystical things happen

**Comment by jadoc** [comment]
Pull request #134 was meant to fix an issue related to waiting for output when the server is paused, but it also introduces a sleep when output is expected. It's a hack, but may help with this issue. Though, the entire output extraction logic is already a hack, so maybe this is the best that can be done.

**Comment by Bisa** [comment]
it's a hack indeed, if I come around to looking at this I hope the third invocation of this script will be better ;)
