### ISSUE TITLE
Super slow to stop server.

### ISSUE THREAD

**Issue by viztor** [Bisa/factorio-init#136]
It seems to have some problem with the while loop, and even though it's super fast to load, and start, it's extremely slow to stop the server

**Comment by jadoc** [comment]
Was the server paused when you experienced this issue?

**Comment by viztor** [comment]
No. Do I need to?

**Comment by viztor** [comment]
I asked all to quit before I reload, so the server should be automatically paused.

**Comment by jadoc** [comment]
Ah, in that case, I think case I think this issue is resolved by existing pull request #134 .
