### ISSUE TITLE
./factorio update does not follow UPDATE_EXPERIMENTAL

### ISSUE THREAD

**Issue by Valkyrien04** [Bisa/factorio-init#144]
server will not update off .17.4 despite the latest version being .17.9 and UPDATE_EXPERIMENTAL=1

**Comment by Valkyrien04** [comment]
nevermind, its an issue with the updater script https://github.com/narc0tiq/factorio-updater/issues/45

**Comment by tmzasz** [comment]
yes they somehow broke their own updaters during .17's early releases too
