### ISSUE TITLE
Factorio Mod Manager integration

### ISSUE THREAD

**Issue by Tantrisse** [Bisa/factorio-init#152]
Hi guys !

I'm currently using Factorio-Init and Factorio-Updater and I love the integration of Updater in Init.

But a feature I missed hard was Mod management.
I love to play mod, and managing mod on headless is pain in the ass (tedious updating, enabling / disabling....), so I wrote my own script to manage mods ( https://github.com/Tantriss/Factorio-mods-manager ).

I would love to have it integrated to Factorio-Init in order to manage all my Factorio process with one entry-point !
It has the same dependencies as Factorio-Updater (python 2/3 with Requests) so nothing new here.

Are you guys interested in it or Factorio-Init should not embark to much things ?

Thx ! :)

**Comment by Bisa** [comment]
@Tantrisse - love the idea! :)
