### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DIYglenn** [Bisa/factorio-init#153]
**Describe the bug**
factorio autocomplete wouldn't work
**To Reproduce**
Follow readme and install script

**Expected behavior**
Writing "factorio" in shell and double-clicking tab should autocomplete, but didn't.

I had to run the following command to make it work:
`sudo ln -s /opt/factorio-init/factorio /usr/local/bin/factorio`

**Comment by tmzasz** [comment]
the instructions give you the steps to add autocomplete to your install

Autocompletion

    Copy/Symlink or source the bash_autocompletion file

ln -s /opt/factorio-init/bash_autocomplete /etc/bash_completion.d/factorio
OR:
echo "source /opt/factorio-init/bash_autocomplete" >> ~/.bashrc
restart your shell to verify that it worked

keep in mind if this does not work you may need to install bash_completion from your distro repos

**Comment by ryanmortier** [comment]
I have the same issue. Brand new install of Ubuntu 18.04. Followed the instructions exactly. Tried both the symlink and the ,bashrc file but it doesn't work. bash-completion is installed already. Not sure how to debug or troubleshoot this.

**Comment by DIYglenn** [comment]
Did you try the command I used?:
`sudo ln -s /opt/factorio-init/factorio /usr/local/bin/factorio`
This did solve it for me.

**Comment by ryanmortier** [comment]
Yes that's what I ended up doing and it's working.
