### ISSUE TITLE
[BUG] Script does not start in Screen session

### ISSUE THREAD

**Issue by Chaoschaot232** [Bisa/factorio-init#155]
Not sure why, but it is horrible, that the script does not use screen to have the ability to look what is going on in the console.

Means now, that I must use the old pice of code to have it in a screen session.

Not sure, why this bug wasn't fixed from the hole beginning as screen is not hard to install or to use.

Please fix this, thanks.

**Comment by Bisa** [comment]
I've consciously moved away from screen - you can tail the logs or run the  "cmd"-command to interact with the running process.

It's not a bug, it's a feature ;)
