### ISSUE TITLE
Need some help with standalone server

### ISSUE THREAD

**Issue by Deffie6** [Bisa/factorio-init#163]
Hello,

I`m new on this so sorry for maybe the wrong question or not read the whole story.

I have a linux dedicated services running, but i don`t understand how your script excacly works.
Did not install factorio on the server, I just downloaded the headless server and stored the executeable file in the home dir.
This is like this :

/home/factorio/Services/Factorio_a/
# here I put all the files.
- home -> factorio -> Services -> Factorio_a -> Settings
- home -> factorio -> Services -> Factorio_a -> bin
- home -> factorio -> Services -> Factorio_a -> config
- home -> factorio -> Services -> Factorio_a -> data
- home -> factorio -> Services -> Factorio_a -> mods
- home -> factorio -> Services -> Factorio_a -> saves
- home -> factorio -> Services -> Factorio_a -> scenarios
etc...

Now I want to run you script, but seems i get errors like the config file not found... etc..
Where do I change the PATHS and on wich lines?

the reason i did not install the game on the linux server, is that i want to run other programm`s as well.

Maight be wrong, but this is how i always did it and I had help from a good friend of me, he really understand linux much better than me, but during hi`s jobs and other work, he has no time to help me out.
I am like a linux noob, but I understand some of the commands and know how to use them.

So can you help me out?
Currently I run it when I logged in.
factorio version : 0.18.21 (test)
SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux.

Thanks for the help in advanced.

Regards,

**Comment by Bisa** [comment]
Hi, did you rename the "config.example" to just "config" yet?
(that's the file where you change most of the settings/paths etcetera, if you need more debug output that's where you enable debugging)

Once you have that sorted, try running:
/path/to/factorio-init-script/factorio start

**Comment by Deffie6** [comment]
> Hi, did you rename the "config.example" to just "config" yet?
> (that's the file where you change most of the settings/paths etcetera, if you need more debug output that's where you enable debugging)
> 
> Once you have that sorted, try running:
> /path/to/factorio-init-script/factorio start

And where must the config.example be in? can`t find it.
As i said, i didn`t install the game on my server.

**Comment by Bisa** [comment]
You will need to download this script, and the config.example file to start with.
Then, if you want the script to install for you, try the install option - or manually download and unpack the server from factorios official page.

To get you started, try:
- cloning this repo to your /opt folder
  `cd /opt && git clone https://github.com/Bisa/factorio-init.git`
- copy the example config
  `cp config.example config`
- Create a folder for factorio (the game) to live in
  `mkdir /opt/factorio`
  `chown factorio:factorio /opt/factorio`
- install the game using this script
  `/opt/factorio-init/factorio install`
- Start the game
  `/opt/factorio-init/factorio start`

If you run into any issues with the last two steps - try changing DEBUG=0 to DEBUG=1 in the /opt/factorio-init/config file and try the command again, paste any output here and I'll see what I can do.

**Comment by jgradzki** [comment]
Hi, can you explain to me how can i have both file and directory named "config" on linux? :)
Directory is generated by server.

I started server with "standard" way, but i see configuration is now from data folder so i guess i can delete config folder, but anyway i changed "config" file name (in script too)

**Comment by Bisa** [comment]
> Hi, can you explain to me how can i have both file and directory named "config" on linux? :)
> Directory is generated by server.

@jgradzki 
I'm afraid you cannot have two items in the same location on most unix filesystem (if not all?) with the same name.

The config (a directory) generated by the server: [factorio install dir]/config
The config (a file) used by my init script needs to live next to the actual init script, as suggested by most guides: /opt/factorio-init/config

If you installed my script in the [factorio install dir] you will need to move it out of that directory and update your PATH to reflect the change.
