### ISSUE TITLE
factorio.service does not start in screen

### ISSUE THREAD

**Issue by chaos234** [Bisa/factorio-init#17]
The factorio.service does not start the factorio server in the prefered screen session.

All was set uped over the non-root user, the root-user was used to create the symlinks and to use the systemctl cmd.

Please fix this issue so that the server can run as service in a screen session (important)!

**Comment by chaos234** [comment]
I should admit that I want to have a console instand

**Comment by Bisa** [comment]
systemctl relies on the binary running a process, there is no screen involved.
Try using the sysvinit approach instead.

ie symlink the script to /etc/init.d/factorio and use "service factorio [command]"

**Comment by chaos234** [comment]
Ah ok, thanks for your replay :).

Am 04.11.2015 um 13:40 schrieb Bisa:

> systemctl relies on the binary running a process, there is no screen 
> involved.
> Try using the sysvinit approach instead.
> 
> ie symlink the script to /etc/init.d/factorio and use "service factorio "
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Bisa/factorio-init/issues/17#issuecomment-153708879.

## 

DeltaNet - Production
Inh. Marcel Petzold
Friedrich-Ebert-Str. 44
04416 Markkleeberg

Mobil: 01728006598
Mail: info@deltanet-production.de

StNr.: 235/256/06058
UStNr.: DE272999582
