### ISSUE TITLE
Integrate @astevens mod updater

### ISSUE THREAD

**Issue by nick4333** [Bisa/factorio-init#170]
@astevens mod updater works nicely and I was wondering if there could be some integration into factorio init, similar to how @narcotiq has made a factorio update script that has been integrated into the factorio init script.

**Comment by Bisa** [comment]
https://github.com/Tantrisse/Factorio-mods-manager.git is already integrated, see "./factorio mod help" - for now that's sufficient imo, but feel free to suggest adaptions/changes as you see fit :)
