### ISSUE TITLE
step by step instructions should mention requirements

### ISSUE THREAD

**Issue by idprism** [Bisa/factorio-init#171]
both curl and wget are called from the factorio script, however, when attempting `factorio install` i simply got warning "unable to download & cache" without any mention of why. never expected to have to install wget, since it wasn't mentioned anywhere.

would be nice to get a double-check step in there like:
* sudo dnf install curl wget bash-completion

**Comment by tmzasz** [comment]
I can see wget not being installed as a oversight but most if not all *nix distros usually come with some version of curl

**Comment by idprism** [comment]
@tmzasz if you're going to ensure one why not ensure the other? There's no reason to avoid asking the package manager to verify that it is installed if it's a dependency. Anyway, thanks to Bisa for getting it done. Much appreciated.

**Comment by tmzasz** [comment]
not saying its a bad idea just mentioning the fact listing curl as a requirement is kinda redundant as most have it ( there are exceptions to this on some distro's though)
