### ISSUE TITLE
Start the services gives this issue

### ISSUE THREAD

**Issue by Deffie6** [Bisa/factorio-init#172]
factorio@FS-Master:~$ systemctl start factorio
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to start 'factorio.service'.
Multiple identities can be used for authentication:
 1.  factorio,,, (factorio)
 2.  Alex,,, (outsider)
Choose identity to authenticate as (1-2): 1
Password:
==== AUTHENTICATION COMPLETE ===
Failed to start factorio.service: Unit factorio.service not found.
factorio@FS-Master:~$

**Comment by Bisa** [comment]
You need to run systemctl as a user that has access to do so, try running systemctl as root or with sudo.
