### ISSUE TITLE
Doesn't work for Factorio Headless server 1.0.0

### ISSUE THREAD

**Issue by LukevanTricht** [Bisa/factorio-init#175]
I'm trying to use this to set up a new Factorio server, and it's reporting an error on `./factorio install`

```
Length: 44843968 (43M) [application/octet-stream]
Saving to: 'STDOUT’

-                                                 0%[                                                                                                     ]       0  --.-KB/s               tar: 
Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
-                                                 0%[                                                                                                     ]  15.67K  --.-KB/s    in 0.02s


Cannot write to '-’ (Success).
Aborting install, unable to download and extract tarball.
```

**Comment by ErikEvenson** [comment]
Are you running as the user you setup in config?  Does that user have write permission?

**Comment by LukevanTricht** [comment]
> Are you running as the user you setup in config? Does that user have write permission?

Yes and Yes.

I'm not sure if it was something on WUBEs end, or something wrong with the specific 1.0.0 archive, but I just ran it again to grab the exact environment/commands etc for you, and it worked with the 1.1.19 server files.
