### ISSUE TITLE
runaway cat on fifo file when factorio stop is issued

### ISSUE THREAD

**Issue by tmzasz** [Bisa/factorio-init#185]
when issuing factorio stop the tail on the server fifo gets replaced with a runaway cat that sits there using ram doing nothing on the root user 
https://cdn.discordapp.com/attachments/627326922573086730/827397634355757057/unknown.png

**Comment by Bisa** [comment]
Which system are you running this on?
The code was introduced to fix another problem , see [d601a6082c4eccef07909f5d1c90dd7942c4518c](https://github.com/Bisa/factorio-init/commit/d601a6082c4eccef07909f5d1c90dd7942c4518c)

Before I can accept the PR you made I'd need some test coverage to ensure the original issue does not return.
#helpwanted - or I'll get around to writing them myself at some point :)

**Comment by tmzasz** [comment]
ok so the system is CentOS Linux release 7.9.2009 (Core) using kernel 4.9.178
Yea i saw that but the issue it seems is the intended stop to the pipe does not actualy stop the pipe like it should as the opening cat ${FIFO} & command seems to prevent it from closing with the echo commands ( it still hangs ). Removing the cat ${FIFO} & part seems to allow the echo to properly close the cat.

**Comment by tmzasz** [comment]
so from what I can gather so far the fix does stop the run away cat on my machine ( tested through several factorio stop and box reboots now ) i think the manual startup of the reader is not necessary in this instance because the FIFO is already being tailed in the start_service() function on line # 319 and is just serving to open a second reader which results in a runaway cat
