### ISSUE TITLE
Some pingpong server don't respond. And the server is not visible in game list.

### ISSUE THREAD

**Issue by YagaoDirac** [Bisa/factorio-init#188]
No idea if this is caused by instability or some other problems.
The server works properly until we decide to restart it yesterday with a new save file. The save file is created with my new scenario. I don't know if the update in the scenario causes the problem. I tried a very vanilla freeplay save file, it failed too.

**Comment by Bisa** [comment]
Hey, what happens if you start the server manually? (without this startup script)
