### ISSUE TITLE
Systemd serivce times out on Fedora 35

### ISSUE THREAD

**Issue by NovaPhoenix** [Bisa/factorio-init#192]
Hi, when using the provided systemd service file modified for my installation I always get this as output:
`Job for factorio.service failed because a timeout was exceeded. See "systemctl status factorio.service" and "journalctl -xeu factorio.service" for details.`
It starts the game server then 20 seconds later after the timeout shuts it down.
Journalctl output: https://gist.github.com/NovaPhoenix/24bfe2add40420b4a4538c259c59fbb5
Service file contents: https://gist.github.com/NovaPhoenix/8db0c39c503870d031df78d8eff28a31
The factorio user has permission to write and read in that directory, as I have been using it to run a chat bridge inside a subdirectory of that and I can `touch server.pid`, though it gets deleted after the service runs. The game runs fine when the script is manually started.

**Comment by Bisa** [comment]
'fraid I'm not super used to systemd - but what user is trying to open the pidfile? and can you confirm that the pidfile exists within 20 seconds of starting the service?

**Comment by Bisa** [comment]
if anyone else runs into this - feel free to help out debugging (either ping me here or open a new issue)
