### ISSUE TITLE
Combatibility issue with WSL2/Ubuntu

### ISSUE THREAD

**Issue by SirDragonClaw** [Bisa/factorio-init#195]
Hey I have been trying to install this for the last hour or so and have gotten past a few issues but it still wont install. I have it failing to extract the archive now.

If anyone can make sense of this that would be great, or perhaps it is an issue with the script?

`daniel@DanStudy:/opt/factorio-init$ bash factorio install
Aborting install, unable to write to '/opt/factorio'!
daniel@DanStudy:/opt/factorio-init$ cd /mnt/c/Users/DanAr/Linux/factorio-init
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
Aborting install, unable to write to '/mnt/c/Users/DanAr/Linux/factorio'!
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ cd /mnt/c/Users/DanAr/Linux
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ mkdir factorio
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ cd factorio-init/
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
Run this script as the factorio user!
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ groups
daniel adm dialout cdrom floppy sudo audio dip video plugdev netdev
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/tmp/: Is a directory
Aborting install, unable to download & cache '/tmp/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/tmp/: Is a directory
Aborting install, unable to download & cache '/tmp/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/tmp/: Is a directory
Aborting install, unable to download & cache '/tmp/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ cd ..
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ ls
factorio  factorio-init
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ mkdir tmp
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ cd factorio-init/
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/tmp/: Is a directory
Aborting install, unable to download & cache '/tmp/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ cs ..

Command 'cs' not found, but can be installed with:

sudo apt install csound

daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ cd ..
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ mkdir cache
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ ls
cache  factorio  factorio-init  tmp
daniel@DanStudy:/mnt/c/Users/DanAr/Linux$ cd factorio-init/
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/mnt/c/Users/DanAr/Linux/cache/: Is a directory
Aborting install, unable to download & cache '/mnt/c/Users/DanAr/Linux/cache/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
/mnt/c/Users/DanAr/Linux/cache/: Is a directory
Aborting install, unable to download & cache '/mnt/c/Users/DanAr/Linux/cache/'.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
--2022-03-13 20:04:56--  https://www.factorio.com/get-download/stable/headless/linux64
Resolving www.factorio.com (www.factorio.com)... 104.26.14.88, 172.67.71.197, 104.26.15.88, ...
Connecting to www.factorio.com (www.factorio.com)|104.26.14.88|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=AdE6v0UMy9KAr_Av_fC1qA,1647165898 [following]
--2022-03-13 20:04:57--  https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=AdE6v0UMy9KAr_Av_fC1qA,1647165898
Resolving dl.factorio.com (dl.factorio.com)... 143.244.62.5, 2a02:6ea0:db00::1
Connecting to dl.factorio.com (dl.factorio.com)|143.244.62.5|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52117820 (50M) [application/octet-stream]
Saving to: ‘STDOUT’

-                                    0%[                                                               ]       0  --.-KB/s               tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
-                                    0%[                                                               ]  15.56K  --.-KB/s    in 0.02s

Cannot write to ‘-’ (Success).
Aborting install, unable to download and extract tarball.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ sudo bash factorio install
--2022-03-13 20:05:15--  https://www.factorio.com/get-download/stable/headless/linux64
Resolving www.factorio.com (www.factorio.com)... 104.26.14.88, 172.67.71.197, 104.26.15.88, ...
Connecting to www.factorio.com (www.factorio.com)|104.26.14.88|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=crhUg41P-qgn_r63Im7Dkw,1647165916 [following]
--2022-03-13 20:05:15--  https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=crhUg41P-qgn_r63Im7Dkw,1647165916
Resolving dl.factorio.com (dl.factorio.com)... 143.244.62.6, 2a02:6ea0:db00::1
Connecting to dl.factorio.com (dl.factorio.com)|143.244.62.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52117820 (50M) [application/octet-stream]
Saving to: ‘STDOUT’

-                                    0%[                                                               ]       0  --.-KB/s               tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
-                                    0%[                                                               ]  15.56K  --.-KB/s    in 0.02s

Cannot write to ‘-’ (Success).
Aborting install, unable to download and extract tarball.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ sudo bash factorio install
DEBUG: Check/Loading config defaults for command 'install'
DEBUG: Skip check/loading defaults for command 'install'
DEBUG: Checking for latest headless version.
DEBUG: Found, latest version: ''
DEBUG: as_user: wget -O - "https://www.factorio.com/get-download/stable/headless/linux64" |tar --strip-components 1 -xC "/mnt/c/Users/DanAr/Linux/factorio"}
--2022-03-13 20:07:37--  https://www.factorio.com/get-download/stable/headless/linux64
Resolving www.factorio.com (www.factorio.com)... 104.26.14.88, 172.67.71.197, 104.26.15.88, ...
Connecting to www.factorio.com (www.factorio.com)|104.26.14.88|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=uSe-abIpnb8NFO8-o6qygQ,1647166059 [following]
--2022-03-13 20:07:38--  https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=uSe-abIpnb8NFO8-o6qygQ,1647166059
Resolving dl.factorio.com (dl.factorio.com)... 143.244.62.6, 2a02:6ea0:db00::1
Connecting to dl.factorio.com (dl.factorio.com)|143.244.62.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52117820 (50M) [application/octet-stream]
Saving to: ‘STDOUT’

-                                    0%[                                                               ]       0  --.-KB/s               tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
-                                    0%[                                                               ]  15.56K  --.-KB/s    in 0.02s

Cannot write to ‘-’ (Success).
Aborting install, unable to download and extract tarball.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$ bash factorio install
DEBUG: Check/Loading config defaults for command 'install'
DEBUG: Skip check/loading defaults for command 'install'
DEBUG: Checking for latest headless version.
DEBUG: Found, latest version: ''
DEBUG: as_user: wget -O - "https://www.factorio.com/get-download/stable/headless/linux64" |tar --strip-components 1 -xC "/mnt/c/Users/DanAr/Linux/factorio"}
--2022-03-13 20:07:57--  https://www.factorio.com/get-download/stable/headless/linux64
Resolving www.factorio.com (www.factorio.com)... 104.26.14.88, 172.67.71.197, 104.26.15.88, ...
Connecting to www.factorio.com (www.factorio.com)|104.26.14.88|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=HHHiVST7FzO5WZm7Fy5whA,1647166078 [following]
--2022-03-13 20:07:57--  https://dl.factorio.com/releases/factorio_headless_x64_1.1.53.tar.xz?secure=HHHiVST7FzO5WZm7Fy5whA,1647166078
Resolving dl.factorio.com (dl.factorio.com)... 143.244.62.6, 2a02:6ea0:db00::1
Connecting to dl.factorio.com (dl.factorio.com)|143.244.62.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 52117820 (50M) [application/octet-stream]
Saving to: ‘STDOUT’

-                                    0%[                                                               ]       0  --.-KB/s               tar: Archive is compressed. Use -J option
tar: Error is not recoverable: exiting now
-                                    0%[                                                               ]  15.56K  --.-KB/s    in 0.02s

Cannot write to ‘-’ (Success).
Aborting install, unable to download and extract tarball.
daniel@DanStudy:/mnt/c/Users/DanAr/Linux/factorio-init$`

**Comment by SirDragonClaw** [comment]
I have just confirmed that all the same issues happen with a raw install of ubuntu on metal.

**Comment by ask-compu** [comment]
same problem on a fresh linode ubuntu 20.04 server

**Comment by Bisa** [comment]
should be closed by #198 - please give it a whirl if you are still looking to use this script :)
