### ISSUE TITLE
Failed to start, aborting.

### ISSUE THREAD

**Issue by xenadmin** [Bisa/factorio-init#30]
Hello,
today I tried your script on Ubuntu 14.04.4 LTS but without success. I always get the error, leaving open processes:
`root@mc:/opt/factorio# service factorio start`
`Still not running, waiting a while longer...`
`Failed to start, aborting.`
`root@mc:/opt/factorio# ps -Af | grep fac`
`factorio 31747     1  0 13:56 ?        00:00:00 SCREEN -dmS factorio /opt/factorio/bin/x64/factorio --start-server factorio-init-save --autosave-interval 3 --autosave-slots 6 --latency-ms 250 --disallow-commands --peer-to-peer`
`factorio 31748 31747  0 13:56 pts/3    00:00:00 /opt/factorio/bin/x64/factorio --start-server factorio-init-save --autosave-interval 3 --autosave-slots 6 --latency-ms 250 --disallow-commands --peer-to-peer`
`root     31882 29998  0 13:58 pts/0    00:00:00 grep --color=auto fac`
`root@mc:/opt/factorio#`
These open processes block the port so I have to kill them. 
According to the log, everything is fine I assume:

> root@mc:/opt/factorio# cat factorio-current.log
>    0.000 2016-03-18 13:56:34; Factorio 0.12.26 (Build 17762, linux64)
>    0.052 Operating system: Linux (Ubuntu 14.04)
>    0.052 Program arguments: "/opt/factorio/bin/x64/factorio" "--start-server" "factorio-init-save" "--autosave-interval" "3" "--autosave-slots" "6" "--latency-ms" "250" "--disallow-commands" "--peer-to-peer"
>    0.052 Read data path: /opt/factorio/data
>    0.052 Write data path: /opt/factorio
>    0.052 Binaries path: /opt/factorio/bin
>    0.061 Running in headless mode
>    0.064 Loading mod core 0.0.0 (data.lua)
>    0.066 Loading mod base 0.12.26 (data.lua)
>    0.427 Factorio initialised
>    0.428 Info Router.cpp:556: Router peerID(65535) shutting down.
>    0.428 Info Router.cpp:582: Router state -> Disconnected
>    0.428 Info MultiplayerManager.cpp:906: networkTick(0) mapTick(-1) changing state from(Ready) to(PreparedToHostGame)
>    0.428 Info MultiplayerManager.cpp:906: networkTick(0) mapTick(-1) changing state from(PreparedToHostGame) to(CreatingGame)
>    0.428 Loading map /opt/factorio/saves/factorio-init-save.zip
>    0.459 Info Scenario.cpp:124: Map version 0.12.26-0
>    0.709 Info MultiplayerManager.cpp:282: 0x7f5f997896e0, (nil)
>    0.709 Info PosixUDPSocket.cpp:34: Opening socket at port 65353
>    0.709 Info Router.cpp:582: Router state -> Connected
>    0.709 Info Synchronizer.cpp:54: NetworkTick(0) initialized Synchronizer local peer(0) latency(15).
>    0.709 Hosting game at port 65353, peerID 0, session magic 2122
>    0.709 Info MultiplayerManager.cpp:304: 0x7f5f997896e0, 0x7f5f997896e0
>    0.709 Info MultiplayerManager.cpp:906: networkTick(0) mapTick(1235041) changing state from(CreatingGame) to(InGame)
>    0.709 Info NetworkInputHandler.cpp:40: mapTick(1235041) networkTick(0) initialized NetworkInputHandler local peer(0).
>    0.976 Info MultiplayerManager.cpp:1385: Received peer info for peer(0) username(<server>).
>    0.976 Info MultiplayerManager.cpp:1043: networkTick(15) mapTick(1235041) received stateChanged peerID(0) oldState(Ready) newState(CreatingGame)
>    0.976 Info MultiplayerManager.cpp:1043: networkTick(15) mapTick(1235041) received stateChanged peerID(0) oldState(CreatingGame) newState(InGame)
> root@mc:/opt/factorio#

Du you have any idea why your script says the server doesn't start?

**Comment by xenadmin** [comment]
The debug Says, it can't find the PID, but I'm not sure why it doesn't get created.

> root@mc:/opt/factorio# service factorio start
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: last modified save: /opt/factorio/saves/factorio-init-save.zip
> DEBUG LOG: using existing factorio-init-save.zip
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> Still not running, waiting a while longer...
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"
> DEBUG LOG: could not find a pid for binary: "/opt/factorio/bin/x64/factorio"

The file permissions are ok, the user can create the file itself.

> root@mc:/opt/factorio# su factorio
> factorio@mc:/opt/factorio$ touch /opt/factorio/bin/x64/factorio.pid
> factorio@mc:/opt/factorio$ ls -lah /opt/factorio/bin/x64/
> insgesamt 53M
> drwxr-xr-x 2 factorio factorio 4,0K Mär 18 14:12 .
> drwxr-xr-x 3 factorio factorio 4,0K Mär 16 22:30 ..
> -rwxr-xr-x 1 factorio factorio  53M Mär  6 01:16 factorio
> -rw-rw-r-- 1 factorio factorio    0 Mär 18 14:12 factorio.pid
> factorio@mc:/opt/factorio$

**Comment by xenadmin** [comment]
Forget it, it was my fault. I changed the service name in the config, that broke your script.

`# What do you want to call this service?`
`SERVICE_NAME="factorio"`

Perhaps you should add a note to this section. Your current statement suggested me that its safe to switch this value, but I assume the name is hard coded in the init script?

**Comment by Bisa** [comment]
My intention is for the configuration to be configurable, thx for reporting
this - I'll have a look at it tonight

**Comment by Bisa** [comment]
@ZomboBrain 
(did you get the latest commit from master?)

The function find_pid() might not be working correctly, as seen on [L99](https://github.com/Bisa/factorio-init/blob/master/factorio#L99) It uses the SCREEN_NAME variable, have you overwritten the screen name at some point?
    pid=$(ps ax | grep -v grep | grep "${BINARY} --start-server ${SAVE_NAME}" | grep -v "${SCREEN_NAME}" | awk '{ print $1}')

I'll tinker with this a bit, please stay tuned.

**Comment by xenadmin** [comment]
Today I have time to test this. 
What would be the right way to update the git clone? I'm no expert here. Normallay I would delete the folder and just clone again ^^"

**Comment by Bisa** [comment]
I've built this so that you should ideally just have to do a git pull (if you are on the master branch) to get the latest and greatest, any config options that are required but missing will be screaming out loud first time you try to run the script (not that smooth I confess but meh ;)

so, in this case:
git pull
check the config.example if I've added anything that concerns you and update your own config

**Comment by xenadmin** [comment]
I think I just act stupid -.-

> root@mc:/opt# git clone https://github.com/Bisa/factorio-init.git
> fatal: Zielpfad 'factorio-init' existiert bereits und ist kein leeres Verzeichnis.
> root@mc:/opt# git pull https:////github.com/Bisa/factorio-init.git
> fatal: Not a git repository (or any of the parent directories): .git
> root@mc:/opt#

Ah sorry you need english.

> root@mc:/opt# git clone https://github.com/Bisa/factorio-init.git
> fatal: Folder exists or isn't empty.
> root@mc:/opt# git pull https:////github.com/Bisa/factorio-init.git
> fatal: Not a git repository (or any of the parent directories): .git
> root@mc:/opt#

EDIT:
Found my mistake:

> You have to actually cd into the directory first

**Comment by Bisa** [comment]
aye, git commands need to be executed within the factorio-init or "git project/repository directory" - did this solve your issue?
