### ISSUE TITLE
symlink is correctly working?

### ISSUE THREAD

**Issue by ryo-n** [Bisa/factorio-init#39]
Thanks for creating nice script.

I think that I have to create actual file instead of symlink so that run `systemctl enable factorio.service`

It is the correct command?
`cp /opt/factorio-init/factorio.service /etc/systemd/system/factorio.service`

**Comment by Bisa** [comment]
Looks correct to me, at least if you are on Centos 7 (that's what Im using)

That said tho; Symlinks works fine for me, but a copy would work equally well - at least in terms of functionality (the symlink is a convenience factor in my case)

**Comment by ryo-n** [comment]
Thank you for quick response.
Yes I am using CentOS7. I will check my server configuration.

**Comment by ryo-n** [comment]
FYI 
I needed to run the following command.
`systemctl -f enable /opt/factorio-init/factorio.service`
And I have added factorio.service into boot run service.

thanks.
