### ISSUE TITLE
Save on stop?

### ISSUE THREAD

**Issue by xenadmin** [Bisa/factorio-init#40]
Hello,
I updated my Server from 0.12.28 to 0.12.29 via your script. Now it seem like I have lost 3-5 minutes gameplay time (no desaster). I know all players should disable auto save and the server does the auto save. I set this to 3 minutes. When the last server-auto-save is a few minutes ago and all player quit, does it ever do an auto save again? I then did stop the server and started the update. When I reconnected 2-4 new assembler buildings where missing. Does the server/script save when I stop it?

**Comment by Bisa** [comment]
I use the same stop method for all stop activity, unless something changed in factorio itself it should save when receiving a stop signal (kill in this case) - you should be able to test this out by using "factorio stop" between two autosaves and verifying the results - if you find anything, please report back :)

**Comment by Bisa** [comment]
Turns out this was a bug in 0.12.30
https://forums.factorio.com/viewtopic.php?f=30&t=23342
