### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by chrisvdwerf** [Bisa/factorio-init#41]
Hello,

I'm getting the following message when doing "service factorio start":
"Check Permissions. Cannot Write to /opt/factorio-init/Factorio.pid. Correct the permission and then execute /etc/init.d/factorio status"
I've done chmod 777 and have tried different groups with chown and using -R for the files inside (since I can't go in the directory because it isn't one (?)). 

I'm still fairly new to using ssh and might have made a dumb mistake. If so, sorry. 

Thanks in advance for answering.

**Comment by Bisa** [comment]
which user are you running factorio as? (I'm going to assume "factorio")

in your case, try this:

```
chmod 770 /opt/factorio-init
chown factorio: /opt/factorio-init
service factorio start
```

This will make the user factorio owner of the /opt/factorio-init directory, it will also assign the group factorio - and set permissions on the directory that allows the owner/group to enter the dir and read/write inside it.

**Comment by chrisvdwerf** [comment]
The directory itself and all the files inside it belong to me using chown. (they used to be root). AND I've given write, read and execute permissions on all files using chmod. I'm still getting the same error.

 I forget to mention it, but I do get the error: 'no passwd entry for user 'factorio' ' twice and an error about a save directory missing.

Thanks for answering!

**Comment by Bisa** [comment]
I'm not entirely sure what you've done but the no passw error seems to suggest you are trying to use a user that does not exist - have you added the user you are trying to use?

**Comment by chrisvdwerf** [comment]
It's the user I created when I installed ubuntu server. So seems to me like a real user. (The naming before the command placement and showing the permissions with ls -l)  But this error only occurs when trying to 'service factorio start', it doesn't occur with commands like accessing files from the user or any other commands/commands from your init script. 

This is the output i'm getting with  'service factorio start':

No passwd entry for user 'factorio' 
No passwd entry for user 'factorio' 
Check Permissions. Cannot Write to /opt/factorio-init/factorio/Factorio.pid. Correct the permissions and then excute: /etc/init.d/factorio status
Error! Save directory missing: /opt/factorio-init/factorio/saves

**Comment by Bisa** [comment]
what user are you running as now? (ie which user are you logged in as?)
if you are not logged in as "factorio"
try this:
~~su -u factorio 'touch /opt/factorio-init/factorio/Factorio.pid'~~

(also try hitting me up on irq.esper.net I'm "Bisa" currently hanging out in the factorio channel)

**Comment by Bisa** [comment]
my bad!

su factorio -c 'touch /opt/factorio-init/factorio/Factorio.pid'

**Comment by Bisa** [comment]
Was solved via irc, mainly by following this guide:
https://wiki.factorio.com/index.php?title=Multiplayer#Linux
