### ISSUE TITLE
Service cannot be started if config/config.ini is not present

### ISSUE THREAD

**Issue by maritaria** [Bisa/factorio-init#45]
This one stumped me for a while, basically I hadn't run the factorio server before and it hadn't generated the default config yet.
If the server is started with --config PATH then that config _must_ exist otherwise it creates an error. That error by the way isnt getting shown because it's created in the screen.

Best to check if the config exists, if not warn the user who is executing the script and tell them to run the server once to have it create a default config

**Comment by Bisa** [comment]
Thank you, good catch
