### ISSUE TITLE
init script not working when EXTRA_BINARGS contains a whitespace at the end

### ISSUE THREAD

**Issue by mojo2012** [Bisa/factorio-init#47]
I had to remove the "peer to peer" flag to make the server work for more than two players.
But I forgot a trailing whitespace - and suddenly the script didn't work anymore.
Even in the debug mode I spent an hour to find out that the whitespace was the mistake.
So could you add a comment there - and maybe remove the peer to peer flag also?

**Comment by Bisa** [comment]
Hi, thank you - so leaving the extra bin args option blank causes this behavior, odd, I was never expecting anyone to run a server without extra args any way but I'll have a look at it =)

**Comment by mojo2012** [comment]
Well, it was not without args, just without the "peer-to-peer" flag. It was one flag with a space at the end, that caused the error.

**Comment by Bisa** [comment]
Confirmed, adding a whitespace at the end breaks stuff, but Im not really sure of a "nice" way to resolve it - after all, trailing whitespaces arnt really meant to be part of options.. for now I'll back off, if you have a cool idea how to fix this or verify it in some way please drop me a pull request =)

**Comment by mojo2012** [comment]
Well, for now you could just add a comment ;-)
