### ISSUE TITLE
Experimental

### ISSUE THREAD

**Issue by xenadmin** [Bisa/factorio-init#48]
I use the python script to update the server. I found code in your script to download the experimental version too, but now how to invoke the update for experimental.

**Comment by Bisa** [comment]
Sorry, I can't quite understand what you want to achieve, please elaborate?

**Comment by Bisa** [comment]
hmm, I presume you found the config option EXPERIMENTAL= in config.example, if not please reopen the issue and explain what you were trying to achieve =)

**Comment by kitingChris** [comment]
The python updater has an --experimental switch which he (and me) wants to get called.. To switch on experimental version on updating

**Comment by Bisa** [comment]
@kitingChris is UPDATE_EXPERIMENTAL=1 doing what you expect?

**Comment by kitingChris** [comment]
Looks like that is it :D 
Thanks
