### ISSUE TITLE
Enhancement - More options.

### ISSUE THREAD

**Issue by kwlockwo** [Bisa/factorio-init#54]
I have added more options to the script which I though were missing.
- new-game: creates a new blank map
- save-game: save the current "factorio-init-save" with the given name.
- list-saves:  List all the saves in the saves folder.  Can be used for input for load-save.

I've attached my script, you could probably do these a little better.

[factorio.zip](https://github.com/Bisa/factorio-init/files/244077/factorio.zip)

**Comment by Bisa** [comment]
Hi, nice of you to share - it would be awesome if you wanted to add these to a pull request? =)

**Comment by kwlockwo** [comment]
Ok, let me try and sort that out.

**Comment by Bisa** [comment]
just a heads up, I'm working on a few fixes in branch issue/#53 so if you want to you can base your pull on that one

**Comment by Bisa** [comment]
cheers, let me know if you need any assistance or what-not =)

**Comment by kwlockwo** [comment]
Done,

**Comment by Bisa** [comment]
noticed, but looked a bit odd - your PR would have reverted a lot of my changes from yesterday, (try merging my master into your branch and only push the changes you made)

**Comment by kwlockwo** [comment]
Yeah wondered about that.  I uploaded my file that was a old one.  Let me make changes to your latest version of the script.

**Comment by Bisa** [comment]
:+1:

**Comment by kwlockwo** [comment]
Ok, I think i've done it now.

**Comment by Bisa** [comment]
still odd, sorry if I'm coming of as ungrateful, really appreciate the effort! =)

3rd times the charm? Try branching off my master and apply your changes then pull request back to my master

**Comment by kwlockwo** [comment]
Yes, I did from the issue#53 branch.  I'll do it from master this time.

On Wed, May 4, 2016 at 2:17 AM, Tobias Bisa Wallin <notifications@github.com

**Comment by Bisa** [comment]
Thnx =) I removed the usage of FACTORIO_PATH and got rid of the list saves command (ls and find are both excellent utils and can take way more parameters than we can support in this script)
