### ISSUE TITLE
factorio.service for upstart

### ISSUE THREAD

**Issue by drakar** [Bisa/factorio-init#57]
Any chance you could enhance the service page and readme to include instructions for upstart users?

Please :+1:

**Comment by Bisa** [comment]
Hi @drakar - I never personally used upstart hence I'm not confident in writing any instructions for it, however if you could provide me with a working example (perhaps in a pull request to the readme file itself I'll be happy to try it out and merge it in if it works)

**Comment by drakar** [comment]
I'm not familiar with it either but if I get it working in Ubuntu 14 LTS I'll send the request.

**Comment by Bisa** [comment]
cheers, thank you! =)

(leaving the issue open in case anyone else is interested till we get it merged)

**Comment by Bisa** [comment]
Looks simple enough: http://upstart.ubuntu.com/getting-started.html

basically add a pre-start refreshing the saves and source the config, followed by a invocation on the binary

I don't have upstart ready to test this so if you want to give it a shot feel free to do so =)

**Comment by drakar** [comment]
I'll test it out for sure!

**Comment by Bisa** [comment]
I'm cutting down on complexity for this repo, feel free to add install instructions for other service managers to the wiki =)
