### ISSUE TITLE
Why abandon systemd?

### ISSUE THREAD

**Issue by petrvecera** [Bisa/factorio-init#66]
Why the systemd was abandoned? I think it was good and also the output from it was quite nice.

Now status is only -  Factorio is running, nothing more. :-1: 

Also it's no longer running as service ?

**Comment by Bisa** [comment]
you can run it as a sysv service if you want to, that was the original idea ;)

I was not able to get my own systemd unit file to work hence I was not confident in keeping it here, if you manage to get it working please throw me a pull request and some instructions to make it simple.

(I will look at adding it again, just not at the moment)

**Comment by Bisa** [comment]
check the development branch, I've added new example units and improved the robustness of figuring out pids a bit - this will definitely go into master down the line hence this ticket isn't really applicable anymore - yay me ;)

**Comment by petrvecera** [comment]
Excellent job! :+1:  Will test once I got home :)
