### ISSUE TITLE
service factorio screen

### ISSUE THREAD

**Issue by xenadmin** [Bisa/factorio-init#69]
I used the "service factorio screen" command very often, to see whats going on. You seem to have removed it. Whats the new way to reach the console output?

**Comment by Bisa** [comment]
try `tail -f /opt/factorio/factorio-current.log`

I'm aware that screen could be used to monitor the servers log but still took the decision to remove it in favor of the pipe input redirection, the exact determination of factorios process id and linux's `tail`

**Comment by xenadmin** [comment]
I just overlooked this file "factorio-current.log" ^^
Was it also there with 0.12.x ?
Does "factorio-current.log" show exactly the same, as if I would run factorio binary from shell without your script? If so, than that's all I need.

**Comment by Bisa** [comment]
not sure, I think chat/commands are not logged there Im afraid, please do some experimentation =)
