### ISSUE TITLE
Odd unhelpful error

### ISSUE THREAD

**Issue by Rhodderz** [Bisa/factorio-init#70]
Hi, sorry to open this as an issue but got an odd error. 
I tried to get the server running via your script and hit a few bumps along the way but currently cant get past this one.
 Unit factorio.service has begun starting up.
Jul 10 17:16:34 RMMD-MC-1 factorio[13734]: DEBUG: Determining WRITE_DIR based on /opt/factorio/config/config.ini, IF you edited write-data from the default, this probably fails
Jul 10 17:16:34 RMMD-MC-1 factorio[13734]: DEBUG: write path: /opt/factorio/bin/x64/../..
Jul 10 17:16:34 RMMD-MC-1 factorio[13734]: Unable to start vana
Jul 10 17:16:34 RMMD-MC-1 factorio[13734]: Could not start vana
Jul 10 17:16:34 RMMD-MC-1 systemd[1]: factorio.service: control process exited, code=exited status=1
Jul 10 17:16:34 RMMD-MC-1 systemd[1]: Failed to start Factorio Server.

This is running on a Centos7 x64 box, Below is my server config and also all the other configs i could think off
`
[root@RMMD-MC-1 factorio]# cat config/config.ini 
[path]
read-data=__PATH__executable__/../../data
write-data=__PATH__executable__/../..
[general]
locale=
[debug]
show_fps=basic
show_detailed_info=basic
show_time_used_percent=basic
show_multiplayer_waiting_icon=basic
show_multiplayer_waiting_statistics=basic
show_tile_grid=full
show_collision_rectangles=detailed
show_selection_rectangles=detailed
show_paths=full
show_next_waypoint_bb=full
show_target=full
show_unit_group_info=full
show_unit_stuck_info=full
show_last_path_detail=full
show_path_cache=full
show_path_cache_paths=full
show_rail_paths=full
show_rolling_stock_count=full
show_rail_connections=detailed
show_rail_segments=detailed
show_rail_joints=detailed
show_train_stop_point=detailed
show_train_braking_distance=full
show_train_signals=full
show_network_connected_entities=detailed
show_circuit_network_numbers=detailed
show_energy_sources_networks=detailed
show_active_state=detailed
show_pollution_values=full
show_active_entities_on_chunk_counts=full
show_active_chunks=full
show_enemy_expansion_candidate_chunks=full
show_tile_variations=full
show_raw_tile_transitions=never
show_tile_correction_previews=never
show_fluid_box_fluid_info=basic
show_environment_sound_info=basic
show_logistic_robot_targets=full
[graphics]
multisampling-level=0
lights-render-quality=0.200000003
fullscreen=false
system-ui-scale=true
custom-ui-scale=1
preferred-screen-index=255
show-smoke=true
show-clouds=true
show-inserter-shadows=true
show-minimap=true
show-pollution-on-minimap=true
show-grid-when-paused=true
show-inserter-arrows-when-detailed-info-is-on=false
show-mining-drill-arrows-when-detailed-info-is-on=true
light-entity-info-background=false
force-opengl=false
graphics-quality=normal
v-sync=true
screenshots_queue_size=10
screenshots_threads_count=1
max-texture-size=0
video-memory-usage=high
disable-fma3=auto
[sound]
master_volume=0.600000024
ambient_volume=0.400000006
game_effects_volume=0.699999988
gui_effects_volume=0.699999988
walking_volume=0.300000012
environment_volume=0.449999988
alert_volume=0.550000012
audible_distance=40
environment_audible_distance=15
maximum_environment_sounds=15
active_gui_volume_modifier=1.29999995
active_gui_environment_volume_modifier=0.600000024
ambient_music_pause_mean_seconds=45
ambient_music_pause_variance_seconds=30
ambient_music_mode=interleave-main-tracks-with-interludes
[other]
tooltip_delay=0.0399999991
max_threads=4
show_tips_and_tricks=true
autosort_inventory=true
research_finished_stops_game=true
use_item_groups=true
use_item_subgroups=true
output_console_delay=1200
autosave_interval=2
autosave_slots=3
enable_latency_hiding=true
enable_new_mods=true
port=34197
check_updates=true
enable_experimental_updates=false
proxy=
verbose-logging=false
`

factorio-init config
http://pastebin.com/tRnTqW62
(gave up trying to deal with Githubs "code" for comments)

I can however run the server manually so at present it i running in a screen session.

**Comment by Bisa** [comment]
hmm, beats me I'm afraid - you say starting with the same $INVOCATION currently works?

**Comment by Bisa** [comment]
hit me up on irc esper.net, Im usually around #factorio - or just leave this closed if you resolved the issue on your own (but please post the solution for others to benefit from if possible)
