### ISSUE TITLE
0.14.19 Settings Changes Break Start Script

### ISSUE THREAD

**Issue by jsavko** [Bisa/factorio-init#93]
It looks like the moved several more of the command line args have been moved into the json.  Once again causing the script to fail to load.

It looks to be the auto save frequency and slots

**Comment by Xiretza** [comment]
There are already 3 pull requests open to move those to the json.

**Comment by jsavko** [comment]
I noticed it right after I updated the issue. Was about to make one myself, but figured I should check the open ones first.

**Comment by Bisa** [comment]
looks like all the pull requests have fixed this, I was able to get the script to start a 0.14.19 server just now - thnx for reporting these and kudos to all the nice ppl pushing the fixes this way
