### ISSUE TITLE
Permission?

### ISSUE THREAD

**Issue by tiagoadp** [Bisa/factorio-init#94]
I installed the headless server from factorio, followed the guide, and it runs smoothly, added user factorio:factorio and chowned the folder to factorio:factorio

it works quite good... but when i try to start via the factorio-init, it gives this:

DEBUG: Determining WRITE_DIR based on /root/factorio/config/config.ini, IF you edited write-data from the default, this probably fails
DEBUG: write path: /root/factorio/bin/x64/../..
Check Permissions. Cannot write to /root/factorio/bin/x64/../..

Here is the invocation:

DEBUG: Determining WRITE_DIR based on /root/factorio/config/config.ini, IF you edited write-data from the default, this probably fails
DEBUG: write path: /root/factorio/bin/x64/../..
/root/factorio/bin/x64/factorio --config /root/factorio/config/config.ini --port 34197 --start-server-load-latest --server-settings /root/factorio/online_show.config.json

everything is nicelly configured, and the paths are corrects, any help will be apreciated.

**Comment by Xiretza** [comment]
Some paths are apparently not correct, since your factorio folder is in `/root`. Obviously user "factorio" can't write to (or even read from) anything under `/root`.

**Comment by tiagoadp** [comment]
HOHOHO rigth i have noobs like me... LOL

Just moved the folder and the contents, chowed again to factorio:factorio! its working as espected, tnx for your time ppl! really nice work!
