### ISSUE TITLE
Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by ghost** [Bisa/factorio-init#95]
I get this message everytime I try to start the server with the service command. Any idea why this is happening?

After running "sudo  systemctl list-units -t service --all" this is listed among other entries:
  factorio.service                      loaded    activating auto-restart 

When I try to run that without sudo I get the same error.

I think I figured it out: I tried to start the service as a non root and that may have caused a problem

**Comment by ghost** [comment]
So, I fixed the Failed to connect to bus part...... and now if i run "service factorio status" I get this:
Jan 11 10:35:28 srv44160 systemd[1]: factorio.service: Unit entered failed state.
Jan 11 10:35:28 srv44160 systemd[1]: factorio.service: Failed with result 'exit-code'.

Edit(again):
And again I found the problem: The server-settings file is corupted and needs to replaced.

Now this has become a useless discusion and I have no idia how to delete it :)

**Comment by Bisa** [comment]
oh, glad you found a resolution =)

**Comment by ghost** [comment]
I am new to linux but I learned something new so it worked out fine.
