### ISSUE TITLE
Map generation

### ISSUE THREAD

**Issue by Blauschirm** [Bisa/factorio-init#97]
Hey!
I really like your service thanks for it!

I can't really succeed in using the new-game command. How exactly do I use the map-gen-settings.json with it?

Commands like these don't through errors, but aren't using the map-gen-settings either:
new-game test --map-gen-settings data/map-gen-settings.json
new-game test data/map-gen-settings.json

**Comment by Bisa** [comment]
hmm, not sure the script allows any other arguments than the ones defined in it - this would have to be added as a feature

**Comment by Bisa** [comment]
Actually, this was already implemented in #89 @Blauschirm, silly me for not noticing this earlier ;)
