### ISSUE TITLE
send_cmd dependent functions hang when not executed as root or factorio-user.

### ISSUE THREAD

**Issue by nihilim** [Bisa/factorio-init#99]
issuing `service factorio players` will hang without termination when not ran as root or factorio user.

I believe a root/factorio-user check should be placed at the beginning.
Alas, my bash-fu is not that brilliant to be able to contribute it myself :(

**Comment by Bisa** [comment]
sounds like a good idea, let me see what I can come up with

**Comment by Bisa** [comment]
@nihilim could you give the development branch a spin to see if this resolved the issue for you?
